### ISSUE TITLE
Server-side fs module appears to be incomplete stub when using import or require

### ISSUE THREAD

**Issue by ratiofu** [practicalmeteor/mocha#45] opened 2016-05-30 18:54 UTC
I was trying to write unit tests around some file operations my code is performing and after a bunch of silent failures (see #44), it turns out that the `fs` module is some sort of stub on the server. I am not sure if this is a build issue with `meteor` or related to how tests are run. Example:

`/imports/server/file.tests.js`:

```
import fs from 'fs'

describe('some test suite', function() {
  it('attempt some file operation', function() {
    console.log('IS SERVER', Meteor.isServer)
    console.log(Object.getOwnPropertyNames(fs))
  })

})
```

I would expect the above code to print all the exports available from the [`fs`](https://nodejs.org/api/fs.html) module, but I am getting only
`[ 'existsSync', 'readdirSync', 'statSync', 'watchFile' ]`

My current work-round is to use `Npm.require` instead:

`const fs = Npm.require('fs')`

**Comment by Sizuko** [comment] 2016-05-31 08:51
Got the same problem till yesterday. I tried to use existsSync and readdirSync but they always return undefined.
Is Npm.require working for you?

**Comment by ratiofu** [comment] 2016-05-31 15:52
Yes, that's how I monkey-patched this for now on my end. There generally seems to be a consistent issue with [server-side code being treated (compiled?) as client-side code](https://forums.meteor.com/t/21696/10).

**Comment by rbabayoff** [comment] 2016-06-07 23:03
tmeasday any clues into why that is? Shouldn't fs be stubbed client side only? I'm assuming this has nothing to do with our package but with meteor itself, per @tjconsult, correct?

**Comment by tmeasday** [comment] 2016-06-08 00:34
This sounds like it could be an issue with Meteor's bundling in test mode. Can we get a simple reproduction and an issue at `meteor/meteor`?

Probably a reproduction with a trivial test driver would make sense..something like:

``` js
// the test driver
export Tests = [];
export runTests = () => {
  Tests.forEach(t => t());
}

// in test file
import fs from 'fs';
import Tests from 'meteor/test-driver-package';

Tests.push(() => {
  console.log('IS SERVER', Meteor.isServer);
  console.log(Object.getOwnPropertyNames(fs));
});
```

**Comment by ratiofu** [comment] 2016-06-08 03:21
@tmeasday, I tried to set up [a simple project with a rudimentary test driver](https://github.com/tjconsult/meteor-test-driver) like you suggested above, but I can't get it to run. The `runTests` method is never called.

FWIW, when inspecting the `fs` import outside of the test method, it was the Node version of it, so I am not sure my simple project is even reproducing the problem.

**Comment by tmeasday** [comment] 2016-06-08 04:44
Maybe you need to open the test in the browser?

I realized the sketch I did above doesn't call the tests on the server. This PR adds that: https://github.com/tjconsult/meteor-test-driver/pull/1

And it appears when I run it that it behaves on the server as I would expect.

**Comment by ratiofu** [comment] 2016-06-08 06:09
Yeah, I tried to run it in the browser, too. Thanks for the PR ... and yes, I can't reproduce this in your simple test. Back to square one. I'll take another look.

**Comment by jsep** [comment] 2016-06-09 21:33
Hello @tjconsult @Sizuko 

I just release candidate version that fix this issue.

Just run: `meteor add practicalmeteor:mocha@2.4.5-rc3.1` 

@tmeasday the problem was that I was importing `meteor-node-stubs` in the server and was overwriting some node modules such as `fs`.

Thanks

**Comment by ratiofu** [comment] 2016-06-10 06:02
I updated the package, but that did not result in any changes in `.meteor/versions/` and does _not_ have appeared to fix the issue.

Updating to `-rc3.2` resulted in an update to `mdg:validation-error`, but also did not fix the issue. The server-side test still seems to be using the `fs` stub.

**Comment by jsep** [comment] 2016-06-15 01:05
@tjconsult I've created a PR to your repo that it's working properly for me, let me know any issue please

**Comment by jsep** [comment] 2016-06-22 15:35
Closing this, reopening it not solved

**Closed as completed by jsep** 2016-06-22 15:35 UTC
