### ISSUE TITLE
`merged-stylesheets.css` missing.

### ISSUE THREAD

**Issue by Zodiase** [practicalmeteor/mocha#31] opened 2016-04-13 23:55 UTC
I was testing some visual components and noticed that I couldn't get any CSS/SASS styling to show up. I never encountered anything like this when I was using Velocity. Then I found out that, even though `merged-stylesheets.css` was in the html code sent to the client, it is nowhere to be found in the live DOM. That tells me something is deleting it. I couldn't find any other packages that I'm using my be causing this. So if it is this package that's deleting the CSS file, how can I ask it to stop doing that? And why is it doing that?

![image](https://cloud.githubusercontent.com/assets/1815174/14512952/5793b194-01a9-11e6-9677-56e34eaed74e.png)

![image](https://cloud.githubusercontent.com/assets/1815174/14512954/6054b6e8-01a9-11e6-91ea-dded9a1f2276.png)

**Comment by jsep** [comment] 2016-04-15 19:31
Hello @Zodiase 

Are you running the application with `meteor test` command?
If you run `meteor test` command with `practicalmeteor:mocha` driver package it will only show the web reporter.
Otherwise your application should run as always, `practicalmeteor:mocha` does nothing unless you are running the application in test mode.

**Comment by Zodiase** [comment] 2016-04-15 21:04
@jsep Thanks for replying! I'm using `meteor test --driver-package practicalmeteor:mocha`. Are you saying as long as I'm using `meteor test`, Meteor will remove everything leaving only the web reporter? 

If that's the case, I'd have to just use `meteor run` and write all the tests as part of the app (not in `.tests.` files)?

**Comment by jsep** [comment] 2016-04-15 21:14
@Zodiase according to [Meteor Guide](http://guide.meteor.com/testing.html#test-modes) meteor test command is:

> The primary way to test your application
> This loads your application in a special “test mode”. What this does is:
> - Doesn’t eagerly load any of our application code as Meteor normally would.
> - Does eagerly load any file in our application (including in imports/ folders) that look like `*.test[s].*`, or `*.spec[s].*`
> - Sets the Meteor.isTest flag to be true.
> - Starts up the test driver 

What you can do is to run your tests and your app at the same time for example:
- `meteor run` 
- `meteor test --driver-package practicalmeteor:mocha --port 3100`  

Then go to:
 `http://localhost:3000/` - for your app
 `http://localhost:3100/` - for your tests

I recommend you to read the [Meteor Testing](http://guide.meteor.com/testing.html) for more information about test mode.

**Comment by Zodiase** [comment] 2016-04-15 23:28
@jsep I'm sorry but I don't think you understand what I'm asking... I have read the Meteor Guide over and over but either it's ambiguous about this issue or something else is wrong.

Let me put it this way:

I have:
`/client/foo.tests.js`
`/client/foo.tests.css`

and then I run:
`meteor test --driver-package practicalmeteor:mocha`

Now I can see the test results at `http://localhost:3000/`, but it **doesn't have any CSS I put in `foo.tests.css`**.

**The content of `foo.tests.css` has been sent to the client, as I can see it in the page source, but got deleted by some party after the page is loaded.**

And I'd like to know what is causing this phenomenon.

**Comment by rbabayoff** [comment] 2016-04-18 18:27
@tmeasday ?

**Comment by tmeasday** [comment] 2016-04-19 23:44
@Zodiase - The test driver needs to remove your applications CSS so it doesn't interfere with the test reporters CSS. This is a consequence of how the test mode architecture differs from Velocity.

If you are writing a test case that depends on CSS, you are probably better using an acceptance test: http://guide.meteor.com/1.3-migration.html#full-app-testing

**Comment by rbabayoff** [comment] 2016-05-05 20:53
Closing this, since this is the expected behavior of meteor test without the --full-app flag.

**Closed as completed by rbabayoff** 2016-05-05 20:53 UTC
